image: docker-repository-greenskin.cailleaux.com/greenskin/ci-builder-node14:2.0

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: fetch

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - node -v

build:
  stage: build
  script:
    - npm ci
    - npm run build
    - cp module.json dist
    - cd dist
    - zip wfrp4-enhanced-drag-n-drop-items.zip -r *.* -x ".*"
  artifacts:
    name: wfrp4-enhanced-drag-n-drop-items
    when: on_success
    paths:
      - dist/wfrp4-enhanced-drag-n-drop-items.zip
  when: on_success
  only:
    - tags
    - master

deploy:
  stage: deploy
  script:
    - git config --global user.email "$GIT_USER_EMAIL"
    - git config --global user.name "$GIT_USER_NAME"
    - git add -f dist/wfrp4-enhanced-drag-n-drop-items.zip
    - git commit -m "push artifact on dist branch"
    - git remote set-url origin $GIT_SSH_URL
    - git push origin dist
  only:
    - master
